config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope '/admin' do
    resources :users
  end
  resources :items
  resources :users
  resources :roles
  root 'items#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.seller?
      can :read, Item
      can :create, Item
      can :update, Item do |item|
        item.try(:user) == user
      end
      can :destroy, Item do |item|
        item.try(:user) == user
      end
    elsif user.regular?
      can :read, Item
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :restrict_with_exception
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role, optional: true
  has_many :items, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Regular' if role.nil?
  end

  def admin?
    role.name == 'Admin'
  end

  def seller?
    role.name == 'Seller'
  end

  def regular?
    role.name == 'Regular'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do
    flash[:error] = 'Access denied!'
    redirect_to root_url
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item.user_id = current_user.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :user_id)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
    if @role.users.empty?
      @associated_user = 'None'
    else
      @associated_users = @role.users.map(&:name).join(', ')
    end
  end

  # GET /roles/new
  def new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users or /users.json
  def index
  end

  # GET /users/1 or /users/1.json
  def show
    @joined_on = @user.created_at.to_formatted_s(:short)

    if @user.current_sign_in_at
      @last_login = @user.current_sign_in_at.to_formatted_s(:short)
    else
      @last_login = 'never'
    end
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    successfully_updated = if needs_password?(@user, user_params)
                            @user.update(user_params)
                          else
                            @user.update_without_password(user_params)
                          end
    respond_to do |format|
      if successfully_updated
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def needs_password?(user, params)
      params[:password].present?
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.slim
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

=> link_to 'Show', @item
'|
=< link_to 'Back', items_path

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Name
      th Description
      th Price
      th Seller
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.name
        td = item.description
        td = item.price
        td = item.user.name
        td = link_to 'Show', item
        td
          - if can? :update, item
            = link_to 'Edit', edit_item_path(item)
        td
          - if can? :destroy, item
            = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

- if can? :create, Item
  = link_to 'New Item', new_item_path

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
p#notice = notice

p
  strong Name:
  = @item.name
p
  strong Description:
  = @item.description
p
  strong Price:
  = @item.price
p
  strong Seller:
  = @item.user.name

=> link_to 'Edit', edit_item_path(@item)
'|
=< link_to 'Back', items_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | UserRolesExample
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - if user_signed_in?
      ul
        li Signed in as #{ current_user.email }
        li = link_to 'Edit profile', edit_user_registration_path
        li = link_to 'Sign out', destroy_user_session_path, method: :delete

    - else
      ul
        li = link_to 'Sign up', new_user_registration_path
        li = link_to 'Sign in', new_user_session_path

    - flash.each do |name, msg|
      = content_tag :div, msg, id: "flash_#{name}"

    = yield

app/views/roles/_form.html.slim
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      h2 = "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      ul
        - @role.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/roles/edit.html.slim
h1 Editing role

== render 'form'

=> link_to 'Show', @role
'|
=< link_to 'Back', roles_path

app/views/roles/index.html.slim
h1 Listing roles

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @roles.each do |role|
      tr
        td = role.name
        td = role.description
        td = link_to 'Show', role
        td = link_to 'Edit', edit_role_path(role)
        td = link_to 'Destroy', role, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Role', new_role_path

app/views/roles/new.html.slim
h1 New role

== render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.slim
p#notice = notice

p
  strong Name:
  = @role.name
p
  strong Description:
  = @role.description
p
  strong Assosciated users:
  = @associated_users

=> link_to 'Edit', edit_role_path(@role)
'|
=< link_to 'Back', roles_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :email
    = f.text_field :email

  .field
    = f.label :password
    = f.password_field :password, placeholder: "Leave blank if unchanged"

  .field
    = f.label :role
    = collection_select(:user, :role_id, Role.all, :id, :name, { prompt: true })

  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Role
      th Email
      th colspan='3'

  tbody
    - @users.each do |user|
      tr
        td = user.role.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Role:
  = @user.role.name
p
  strong Email:
  = @user.email
p
  strong Joined on:
  = @joined_on
p
  strong Last logged in on:
  = @last_login
p
  strong No. times logged in:
  = @user.sign_in_count

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path